agent {
    data_dir = "/opt/spire/data/agent"
    log_level = "INFO"
    log_format = "JSON"
    server_address = "spire-server"
    server_port = "8081"
    trust_bundle_path = "/opt/spire/conf/agent/bootstrap.crt"
    trust_domain = "agent-identity-security-control-plane"
    socket_path = "/tmp/spire-agent/public/api.sock"
}

plugins {
    NodeAttestor "k8s_psat" {
        plugin_data {
            cluster = "aicp-cluster"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "k8s" {
        plugin_data {
            skip_kubelet_verification = false
            node_name_env = "MY_NODE_NAME"
        }
    }
}
